project_id = "lsxkhjdfvekjzpjzmwkt"

[functions.demo-login]
verify_jwt = false

[functions.send-fraud-alert-email]
verify_jwt = false

[functions.create-sensor-log]
verify_jwt = true

[functions.create-transaction]
verify_jwt = true

[functions.send-sms]
verify_jwt = false
