project_id = "lsxkhjdfvekjzpjzmwkt"

[functions.demo-login]
verify_jwt = false

[functions.send-fraud-alert-email]
verify_jwt = false

[functions.create-sensor-log]
verify_jwt = true

[functions.create-transaction]
verify_jwt = true

[functions.check-reservation-expiry]
verify_jwt = false

[functions.send-sms-notification]
verify_jwt = true

[functions.generate-overstay-fines]
verify_jwt = false

[functions.send-violation-notification]
verify_jwt = true

[functions.parking-assistant]
verify_jwt = false

[functions.send-review-reply-notification]
verify_jwt = true